name: 🐛 Signaler une erreur ou une anomalie
description: Si vous avez repéré une erreur, une inexactitude ou si un contenu du site ne s'affiche pas convenablement
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Une description claire et concise de l'anomalie rencontrée.
        Ajoutez des copies d'écran si cela peut aider à expliquer le problème (consigne valable pour tous les champs).
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Comportement attendu
      description: Une description claire et concise du comportement que vous vous attendiez à rencontrer.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Comment reproduire l'anomalie
      description: |
        Dans quelles conditions se produit l'anomalie : sur un ordinateur de bureau ou sur mobile ? Avec quel système d'exploitation ? Quel navigateur et version ou quel client REST ?
        Décrivez les étapes pour reproduire le comportement :
        1. Se rendre sur ...
        2. Cliquer sur ...
        3. Scroller jusqu'à ...
        4. Constater l'erreur ...
    validations:
      required: false
  - type: textarea
    id: possible-solution
    attributes:
      label: Solution possible
      description: |
        Optionnel : seulement si vous avez des suggestions pour corriger cette anomalie.
        N'hésitez pas à créer une Pull Request pour avoir un retour plus direct.
  - type: textarea
    id: additional-context
    attributes:
      label: Complément de contexte
      description: |
        Optionnel : Ajoutez toute information qui vous semblerait utile pour nous aider à cerner cette anomalie.